### ISSUE TITLE
DFDL cartridge cannot parse fixed-length files (not finding separator '%NL;')

### ISSUE THREAD

**Issue by skydive241** [smooks/smooks-dfdl-cartridge#249]
**Describe the bug**

I have some problems with DFDL-cartridge compiling the attached dfdl schema and processing the attached file "invoic_03448014.bak" (see below), where the same files can successfully be parsed with daffodil on command line (command like 'daffodil parse --schema "C:\Users\Patrick\eclipse-workspace\smooks-examples\INVOIC02-to-xml\src\main\resources\INVOIC02.dfdl.xsd" C:\Users\Patrick\eclipse-workspace\smooks-examples\INVOIC02-to-xml\INVOIC_03448014.bak').

**To Reproduce**
I attached a small project to reproduce the problem: smooks always gets the exception for not finding the postfix separator '%NL;':

> Caused by: org.smooks.cartridges.dfdl.parser.ParserDfdlSmooksException: Parse Error: Failed to find postfix separator. Cause: Parse Error: separator '%NL;' not found
> Schema context: sequence[1] Location line 33 column 8 in C:\Users\Patrick\eclipse-workspace\smooks-examples\INVOIC02-to-xml\target\classes\INVOIC02.dfdl.xsd
> Data location was preceding byte 2529.
> Schema context: sequence[1] Location line 33 column 8 in C:\Users\Patrick\eclipse-workspace\smooks-examples\INVOIC02-to-xml\target\classes\INVOIC02.dfdl.xsd
> Data location was preceding byte 2005
> 	at org.smooks.cartridges.dfdl.parser.DfdlParser.parse(DfdlParser.java:233)
> 	at org.smooks.engine.delivery.sax.ng.SaxNgParser.parse(SaxNgParser.java:87)
> 	at org.smooks.engine.delivery.sax.ng.SaxNgFilter.doFilter(SaxNgFilter.java:111)
> 	... 5 more
> Caused by: Parse Error: Failed to find postfix separator. Cause: Parse Error: separator '%NL;' not found
> Schema context: sequence[1] Location line 33 column 8 in C:\Users\Patrick\eclipse-workspace\smooks-examples\INVOIC02-to-xml\target\classes\INVOIC02.dfdl.xsd
> Data location was preceding byte 2529.
> Schema context: sequence[1] Location line 33 column 8 in C:\Users\Patrick\eclipse-workspace\smooks-examples\INVOIC02-to-xml\target\classes\INVOIC02.dfdl.xsd
> Data location was preceding byte 2005
> 

**Expected behavior**
In my opinion, smooks and dfdl cartridge should behave like daffodil started from command line - at least I cannot see any reason why it doesn't. I tried all released versions of dfdl cartridge.

**Environment**
Example:
- Smooks: 2.1.0
- Java: dosn't matter, e.g. jre-17.0.6
- Windows 10

**Sample**
[smooks-dfdl.zip](https://github.com/user-attachments/files/18213872/smooks-dfdl.zip)

All files mentioned and the corresponding small project are attached as zip file.

Thanks in advance and greetings from Germany
Patrick

**Comment by cjmamo** [comment]
Thank for reporting this. I confirm there is a problem with how `DfdlParser` handles encoding when converting a `Reader` into `InputStream` (Daffodil does not accept a reader input as far as I can tell). A fix will be in the next release but, in the meantime, as a workaround use `StreamSource` instead of `ReaderSource`. That is:

```java
smooks.filterSource(executionContext, new ReaderSource<>(new InputStreamReader(new ByteArrayInputStream(messageIn), StandardCharsets.UTF_8)), new WriterSink<>(writer));
```

 should become:

```java
smooks.filterSource(executionContext, new StreamSource<>(new ByteArrayInputStream(messageIn)), new WriterSink<>(writer)); 
```

Don't forget to specify the source encoding by setting it on the execution context since your file is encoded in ISO-8859-1 (this should be specified either way because the default encoding in the execution context is set to UTF-8):

```java
executionContext.setContentEncoding("ISO-8859-1");
```

**Comment by skydive241** [comment]
Thank you, I will do what you advice me to! 

By the way: smooks and its cartridges are cool tools!

Greetings and merry christmas,
Patrick
